version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform 1.12.2..."
      - curl -fsSLo terraform.zip https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/terraform
      - terraform version

  pre_build:
    commands:
      - echo "Initializing application Terraform..."
      - terraform init

  build:
    commands:
      - echo "Creating Terraform plan..."
      - terraform plan -out=tfplan

artifacts:
  files:
    - tfplan
