version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - TERRAFORM_VERSION=1.12.2
      - curl -fsSLo terraform.zip https://releases.hashicorp.com/terraform/$\{TERRAFORM_VERSION\}/terraform_$\{TERRAFORM_VERSION\}_linux_amd64.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/terraform
      - terraform version

  pre_build:
    commands:
      - echo "Initializing application Terraform..."
      - terraform init

  build:
    commands:
      - echo "Checking plan artifact..."
      - ls -la "$CODEBUILD_SRC_DIR_plan_output"
      - cp "$CODEBUILD_SRC_DIR_plan_output/tfplan" tfplan
      - echo "Applying Terraform plan..."
      - terraform apply -auto-approve tfplan
